### PR TITLE
clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by stachenov** [comment]
Finally set aside some time for all these piled up PRs and issues.

Unfortunately, I can't just accept this one as it is.

The main reason is that it completely disregards binary compatibility. This is a deal breaker. While I can understand that replacing `QString` with `const QString &` makes perfect sense, it breaks ABI. Note that thanks to implicit sharing this isn't really a big performance concern unless non-const methods are called on those parameters. To guard against that, a local `const` reference can be created that would refer to the formal parameter, which then wouldn't be used anywhere else in the function body.

Also, there are many changes that don't really improve anything. It's no big deal, but they can make future merges more difficult. For example, replacing a local variable type with `auto` does no good, assuming the type was correct to begin with.

Some changes are outright confusing and require very deep knowledge of C++ to even understand whether the change is correct. Example:
```
return QString();
```
This returns a null string.
```
return {};
```
What does this return? A null string? An empty string? It's not obvious. And while I often see it mentioned even in the Qt docs that distinguishing between null and empty strings is a bad idea to begin with, I strongly disagree. There are many places where returning a null string can mean some special case, when an empty string is just a valid value. Moreover, returning an empty string would break the client code if it has an `isNull()` check.

Some changes are very useful, though, like adding `override` or replacing index-based loops with foreach. If you could rework this PR to include only changes that actually improve code substantially, I'll gladly accept it.

**Comment by neheb** [comment]
> Finally set aside some time for all these piled up PRs and issues.
> 
> Unfortunately, I can't just accept this one as it is.
> 
> The main reason is that it completely disregards binary compatibility. This is a deal breaker. While I can understand that replacing `QString` with `const QString &` makes perfect sense, it breaks ABI. Note that thanks to implicit sharing this isn't really a big performance concern unless non-const methods are called on those parameters. To guard against that, a local `const` reference can be created that would refer to the formal parameter, which then wouldn't be used anywhere else in the function body.
> 
> Also, there are many changes that don't really improve anything. It's no big deal, but they can make future merges more difficult. For example, replacing a local variable type with `auto` does no good, assuming the type was correct to begin with.
> 

clang-tidy is overzealous in this sense. auto is very useful for iterators for example.
> Some changes are outright confusing and require very deep knowledge of C++ to even understand whether the change is correct. Example:
> 
> ```
> return QString();
> ```
> 
> This returns a null string.
> 
> ```
> return {};
> ```
> 
> What does this return? A null string? An empty string? It's not obvious. And while I often see it mentioned even in the Qt docs that distinguishing between null and empty strings is a bad idea to begin with, I strongly disagree. There are many places where returning a null string can mean some special case, when an empty string is just a valid value. Moreover, returning an empty string would break the client code if it has an `isNull()` check.
> 
It returns whatever the constructor does.
> Some changes are very useful, though, like adding `override` or replacing index-based loops with foreach. If you could rework this PR to include only changes that actually improve code substantially, I'll gladly accept it.
OK

**Comment by stachenov** [comment]
> It returns whatever the constructor does.

But which constructor? I'm more of a Java programmer for over 15 years now, but I remember reading in one of the Effective C++ books that `{}` strongly prefers constructors accepting an initializer list. So I need to look up QString's doc, check if there's such a constructor () and try to figure what it does in the case the list is empty. And that's _assuming_ `{}` actually calls that constructor and not the default (no-args) one, which I'm not sure is true.

So instead of forcing everybody who happens to read this code to go through this mental gymnastics, I'd rather use `QString()` which explicitly points to the default constructor invocation.

**Comment by neheb** [comment]
Rebased and removed undesired commits.

**Comment by stachenov** [comment]
Looks good to me now, except that there are many weird `if` simplifications, but I'll edit them manually.

**Comment by stachenov** [comment]
No, wait. There's this default comparison operator that isn't supported by the used version of C++. But I guess I'll change that manually too.

**Pull request merged**
