### PR TITLE
Add Flatpak usage in documentation

### PR DESCRIPTION
**Pull request by jacquetc**
Hello,

Here is the little strip of documentation about usage in Flatpak ! Is it enough ?

Regards,
Cyril Jacquet

### CODE REVIEW

**Comment by stachenov** [comment]
Well, I'm not a Flatpak user, so I don't know. I'll apply it and we'll see.

**Comment by jacquetc** [comment]
Well, it works with my software, it's a minimum ! :-)

**Comment by stachenov** [comment]
It's already here:
https://stachenov.github.io/quazip/usage.html

**Comment by jacquetc** [comment]
Great ! Thank you !

**Pull request merged**
