### PR TITLE
Replace deprecated Qt functions with their equivalents

### PR DESCRIPTION
**Pull request by nickdademo**
QFileInfo::created() ->QFileInfo::birthTime()
QObject()::trUtf8() -> QObject()::tr()
qSort() -> std::sort()

### CODE REVIEW

**Comment by stachenov** [comment]
I'm not sure about `QFileInfo::created()` and `qSort()`, but `QObject::trUtf8()` is absolutely needed for Qt4 compatibility, as `QObject::tr()` is rather unreliable there (because it relies on system encoding and `codecForTr()`). Please revert back to `trUtf8()` and check the other two for Qt4 compatibility as well. (And in case anyone wonders whether anyone needs Qt4 these days, we actually *do* presently use it in our company. Sad but true.)

**Comment by nickdademo** [comment]
Hi Sergei,

Thanks for the feedback :)

Here is info on these 3 deprecated functions:
**QFileInfo::created()**
https://doc.qt.io/qt-5/qfileinfo-obsolete.html#created
https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qfileinfo.cpp?h=5.13#n1271
-> Deprecated since 5.10

**qSort()**
https://code.woboq.org/qt5/qtbase/src/corelib/io/qfileinfo.cpp.html#1262
https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/tools/qalgorithms.h?h=5.13#n59
-> Deprecated since 5.2

**QObject::trUtf8()**
https://doc.qt.io/qt-5/qobject-obsolete.html#trUtf8
https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobject.h?h=5.13#n133
-> Deprecated since 5.0

They all now produce compiler warnings too (I'm using the Qt 5.13 branch).

I'm not sure when or if these functions will be removed from Qt in the future (perhaps Qt6?) but maybe the best and most elegant way to ensure building across Qt4, Qt5 and future Qt versions would be to use the QT_VERSION_CHECK() macro. Please see the latest commit in this PR.

**Comment by stachenov** [comment]
Any updates?

**Comment by RichardTea** [comment]
I don't see anywhere that "trUtf8()" is needed at all.
All the strings are Latin1, and thus tr() is fine in Qt4 as well.

So that only leaves the qSort() and QFileInfo::created(), which are only called out once anyway.

**Comment by stachenov** [comment]
Makes sense. I'm so used to Russian strings everywhere at work so I forgot that it isn't a problem for English. Well, no need for an extra unit then. But someone still has to get rid of all those version checks for tr(), leaving only the other two. Maybe I'll get to it when I pull it, if someone doesn't do it before in the PR.

**Comment by nickdademo** [comment]
@stachenov I see that the fixes for this have been merged into `master` - Great! Shall I close this then?

**Comment by stachenov** [comment]
Oh. I thought GitHub closed this automatically. Something went wrong, I guess. Closing now.

**Pull request closed without merging**
