### PR TITLE
Fix CMake find_package for Qt 6

### PR DESCRIPTION
**Pull request by jonaski**
Tested compiling with both Qt 5.15 and Qt 6 (latest Qt dev branch) with the recent CMake changes.
Have to explicitly look for Network and Test too for it to work with Qt 6.

### CODE REVIEW

**Comment by stachenov** [comment]
Wait, even to compile without tests? This looks inconsistent with Qt 5, where it happily compiles with just Core, and if the other components are installed, then tests compile just fine too even if they aren't listed in `find_package`.

What exact error do you get and when?

**Comment by jonaski** [comment]
```
jonas@jonas:~/Projects/jonaski-quazip/build> cmake -DQUAZIP_QT_MAJOR_VERSION=6 ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Configuring done
CMake Error at qztest/CMakeLists.txt:31 (add_executable):
  Target "qztest" links to target "Qt6::Network" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at qztest/CMakeLists.txt:31 (add_executable):
  Target "qztest" links to target "Qt6::Test" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by stachenov** [comment]
*Very* interesting. So it looks like Qt 6 changed semantics of `find_package` so that it only imports targets from explicitly required components. But... it also means that CMake wants these additional targets because `qztest` wants them, regardless of whether `qztest` is included into the build or not... which means that I should require these components for Qt 4/5 as well! Because right now it only works with Qt 4/5 “by coincidence” (with Qt importing what hasn't been asked for), and if I were to try to build QuaZip on a system when on of these targets is unavailable, I'll probably get the same error.

The ideal way to solve this would be to mark these components as optional and only include `qztest` if these were found. I've just done it in `master` for Qt 5. Could you try the same thing with Qt 6 and add another commit to this PR once you make sure it works?

I've deduced these `Qt5Network_FOUND` and `Qt5Test_FOUND` from Qt sources. It simply concatenates the namespace with the name of the module passed to `find_package`. I've checked this with Qt 6 sources, so `Qt6Network_FOUND` and `Qt6Test_FOUND` *should* work.

**Comment by jonaski** [comment]
They didn't change it, you got find_package for Qt5 Network and Test in qztest. See: https://github.com/stachenov/quazip/blob/master/qztest/CMakeLists.txt#L3
I actually didn't see that at first, but was very curious why it worked with Qt5. The whole purpose of find_package with COMPONENTS is to check for the modules you need, you don't automatically get Test and Network by just looking for Core.

But I suggest instead of this: `set(QUAZIP_BUILD_TESTS "no")`
I suggest to change it on an option, e.g.: option(QUAZIP_BUILD_TESTS OFF "Build tests")
(At least change "yes" / "no" string to ON and OFF which is common for CMake).

Then set the required components in a list variable:

set(QT_COMPONENTS Core)

```
if(QUAZIP_BUILD_TESTS)
  list(APPEND QT_COMPONENTS Network Test)
endif()
```

For Qt 6:
```
if(QUAZIP_QT_MAJOR_VERSION EQUAL 6)
  list(APPEND QT_COMPONENTS Core5Compat)
endif()
```

then for each if (QUAZIP_QT_MAJOR_VERSION), do a required for all of them, just replace Qt6 for the other versions:
`
find_package(Qt6 REQUIRED COMPONENTS ${QT_COMPONENTS})`
`

I can make a PR for it if you want to do it that way.

**Comment by stachenov** [comment]
Changed yes/no to ON/OFF, no big deal.

`find_package` for Qt5 in qztest is really a bug. I read somewhere that `find_package` twice is a bad idea, but more importantly, it always looked for Qt5 no matter which major version of Qt QuaZip was configured with. Removed that `find_package`.

I'm not sure I like the idea of making QUAZIP_BUILD_TESTS an option. That would require the user to specifically ask to build tests, which kind of makes no sense when the user runs `cmake --target check`, which already means that they *want* to build tests. What's wrong with the current approach? If the appropriate Qt modules are available, the tests are enabled, but they are only built when the users asks to run tests.

I'm fairly new to CMake, so I don't know what way would be better. For now, I renamed QUAZIP_BUILD_TESTS to QUAZIP_ENABLE_TESTS because they aren't really built just because they can be built.

**Pull request closed without merging**
