### PR TITLE
Add overload to PR8

### PR DESCRIPTION
**Pull request by Sil3ntStorm**
This is #8 with an overload instead of the function change to avoid the mentioned ABI issues.

### CODE REVIEW

**Comment by stachenov** [comment]
First, it conflicts with another PR (the one that fixes includes). Second, since it adds new public functions, a corresponding unit test is needed.

**Comment by Sil3ntStorm** [comment]
The new calls are implicitly tested, as the old API now just calls the new overloads with the `QTextCodec*` parameter.

**Comment by stachenov** [comment]
OK, I'll write a test myself. Because it is still needed. This is not about testing the underlying functionality. This is simply about testing that this new overload works as intended. If I just remove the `if` line, it won't work any longer and it will pass all the tests. This is unacceptable. A very simple test will do just fine.

**Comment by stachenov** [comment]
Done. Merged into both master and pre1.0.

**Pull request merged**
