### PR TITLE
consistent naming for qmake and cmake

### PR DESCRIPTION
**Pull request by bartoszek**
Since there is  `QUAZIP_LIB_VERSION_SUFFIX` in cmake there should be according adjustments to `qmake` project files. Currently `cmake` produces `libquazip5.so` and `qmake` `libquazip.so`...

### CODE REVIEW

**Comment by stachenov** [comment]
I'm not sure it's a good idea. Cmake and qmake are used by different people, and this sudden change will probably annoy qmake people happily using existing scheme. Although I like this scheme, so maybe start using it since Qt6 is a good idea?

**Comment by stachenov** [comment]
I see that related issues are closed, so I'm closing this due to the lack of feedback and the aforementioned reasons.

**Comment by eli-schwartz** [comment]
I'm quite puzzled why one would wish to continue shipping a conceptually broken build system because two linked issues were closed (as implemented!)

At any rate, any consumers of the library would simply have to rebuild their projects, so I fail to see how this would possibly be a bad thing...

Please fix it. Currently Arch Linux is building quazip using cmake to get functioning libraries, then using qmake to generate a pkg-config file, then sed'ing the pkg-config file so that it actually tells the truth about what is installed on the system. You are making it needlessly hard for your downstream users to have any clue how you intend the project to be used.

This is a bug. It needs to be fixed.

**Comment by stachenov** [comment]
OK, let's eat this elephant on a part-by-part basis.

First. I have no clue what you're talking about.

Second. Probably you're right. But I seem to lack specific knowledge to understand that.

Third. I only use qmake myself. CMake files were contributed by someone. I just blindly accept any PRs related to CMake.

Given all that, I agree that it needs to be fixed somehow. The question is, how? I can probably learn CMake pretty quickly, but will that help? I should probably also learn how people actually use build systems to build whatever downstream users need. This is a bit harder because I don't know exactly what they are building and how. OK, you mention Arch Linux. I can figure out how the build for Arch Linux works. THEN it turns out that different distributions use completely different approaches.

I'm just a programmer. I created this library because I myself needed it. Then I just shared it. I personally just build it from source and install using `qmake`. I'm quite happy with this approach because I only need to install it on a few servers at work. I understand that it doesn't work for big Linux distributions. But my knowledge of these distributions are quite limited.

What I really need is a build system maintainer who could take care of all these subtleties and contribute build files that would work consistently across all distributions. Otherwise it's just up to the distribution maintainers to build it the right way, whatever way they think it's right.

I don't really *intend* the project to be used in any particular way. To me, it's just a bunch of C++ classes.

**Comment by eli-schwartz** [comment]
I looked around a bit and it seems like the reason for the clash is this: cc2e8ff9bc45679c3312592cce39ccaf62c66a00

So I guess it would seem that cmake is the inconsistent thing, then? The commit history doesn't say who originally authored the patch, and I guess the project must have switched hosting since then... I would rather like to know what the purpose of the patch was, if it broke cmake/qmake compatibility. :(

**Comment by stachenov** [comment]
Here is the link to the original patch:
https://sourceforge.net/p/quazip/patches/22/

I'm not to judge which build system is inconsistent. Up to this moment I really thought that each distribution chooses its own way to build and it doesn't matter much what build files are shipped with the sources. From your comment, I figure out I was probably wrong. But I still don't quite understand what exactly is the problem and how to fix it.

To make things worse, QuaZIP was originally developed with Qt4, and Qt5 support was added later in an ad-hoc manner, maintaining backwards compatibility. It was never clear how to handle possible conflicts between the two. Add to that the limitations of build systems and different ways of linking on different platforms, and you get exactly the mess we're in.

In an ideal world, someone would just issue a PR that resolves *everything* and makes *everyone* happy. I'm not sure if such a thing is even possible, but I can dream, can't I?

**Comment by eli-schwartz** [comment]
The libraries shipped with Qt5 itself also need to ensure they are only loaded in the right version of Qt, and platformthemes and suchlike get installed to QT_INSTALL_PLUGINS which is a private libdir... the implementation there is to name things libQt5Foo which seems fairly robust. `libquazip5.so` looked like version 5 of quazip. :/

Perhaps changing TARGET to be prefixed with `Qt$$QT_MAJOR_VERSION`, and renaming the pkg-config etc. files similarly, with compatible changes to the CMakeLists.txt, would make sense?

This would ensure that the library and the pkg-config/FindFoo.cmake files would always be predictable (no matter which build system a distributor built it with), and other projects could reliably search for and link to quazip. It would also be forward-compatible with Qt 6 whenever that is released.

You could switch now, but create compatibility pkg-config/FindFoo.cmake symlinks to ensure people looking for the old names would still successfully find quazip.

**Comment by stachenov** [comment]
I don't think keeping compatibility symlinks is the way to go, because that means keeping some of the old mess. You keep talking about CMake and pkg-config, but what about people that just `qmake, make, make install` it? They end up with `libquazip.so`. To maintain compatibility, I'd still need to create `libquazip.so`, even if as a symlink to `libQt5quazip.so`. Which is far from perfect because people will still confuse Qt4 and Qt5 builds, and I'm not even asking a pointless question about what should `libquazip.so` point to if there are Qt4 and Qt5 builds installed simultaneously.

I think the right way to solve it would be to finally release 1.0 without maintaining full backwards compatibility. The project is quite stable anyway. I'll just ditch `libquazip.so` completely and build `libQt${QT_MAJOR_VERSION}quazip.so` with both qmake and CMake.

Except that I still have no clue how to use CMake, and very little experience with pkg-config. And looking and CMakeLists.txt and QuaZipConfig.cmake, I'm not at all sure I want to learn yet another build tool I'll probably never use. It looks quite complicated to me.

I have created the pre1.0 branch for this purpose. I'll start to work on qmake build shortly, but unless someone issues a PR to update CMake build, it'll take me *quite* a while to get to it.

**Comment by bartoszek** [comment]
Just ping me, I'll gladly fix the cmake script :smirk:

**Comment by stachenov** [comment]
The `pre1.0` branch is there for quite a while. I could really use some help with CMake here. All I need is a PR to change produced libraries to libQt5quazip, libQt4quazip and so on. Then I'll do the same thing with qmake, maybe change a few deprecated things and then finally release 1.0. But without CMake update, I just keep merging master into `pre1.0`, which kind of doesn't make sense.

**Comment by zgyarmati** [comment]
I'll issue a PR with the needed cmake  (and possibly also qmake) changes in the next days, and we can review it.

**Comment by stachenov** [comment]
I've created #82 for CMake-related discussion. It's now spread among several issues/PRs, some of which are closed, and that makes hard to keep track of all those and search for them. Please don't post here any more.

**Pull request closed without merging**
